# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-25 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0009_good_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='quantity')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Good', verbose_name='good_item')),
            ],
            options={
                'verbose_name': 'cart_item',
                'verbose_name_plural': 'cart_item',
            },
        ),
    ]
