# Generated by Django 2.0 on 2018-04-26 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aorder',
            fields=[
                ('ordernum', models.AutoField(primary_key=True, serialize=False)),
                ('ID', models.IntegerField()),
                ('description', models.CharField(max_length=120)),
                ('amount', models.IntegerField()),
                ('ups', models.CharField(max_length=120)),
                ('whid', models.IntegerField(blank=True, null=True)),
                ('desx', models.IntegerField(default=0)),
                ('dexy', models.IntegerField(default=0)),
                ('goodid', models.IntegerField(blank=True, null=True)),
                ('truckid', models.IntegerField(blank=True, null=True)),
                ('truck_ready', models.BooleanField(default=False)),
                ('pack_ready', models.BooleanField(default=False)),
                ('load_ready', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('userid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('detail', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='product')),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category')),
            ],
            options={
                'verbose_name': 'good',
                'verbose_name_plural': 'goods',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.PositiveIntegerField(default=0)),
                ('whid', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
