# Generated by Django 2.0 on 2018-04-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uorder',
            fields=[
                ('ordernum', models.IntegerField(primary_key=True, serialize=False)),
                ('ID', models.IntegerField()),
                ('description', models.CharField(max_length=120)),
                ('amount', models.IntegerField()),
                ('ups', models.CharField(max_length=120)),
                ('whid', models.IntegerField()),
                ('desx', models.IntegerField()),
                ('desy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whid', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='aorder',
            old_name='dexy',
            new_name='desy',
        ),
        migrations.AlterField(
            model_name='stock',
            name='gid',
            field=models.IntegerField(),
        ),
    ]
