# Generated by Django 2.0 on 2018-04-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180426_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='image',
            field=models.ImageField(blank=True, default='good', upload_to='img/Alecive-Flatwoken-Apps-Amazon.svg'),
        ),
    ]
