# Generated by Django 2.0 on 2018-04-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20180427_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='image',
            field=models.ImageField(blank=True, default='product/915641_in_pp_ioZkcDv.jpg', upload_to='product'),
        ),
    ]
