# Generated by Django 2.0 on 2018-04-27 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20180427_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='image',
            field=models.ImageField(blank=True, default='img/Alecive-Flatwoken-Apps-Amazon.svg', upload_to='product'),
        ),
    ]
