# Generated by Django 2.0 on 2018-04-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20180427_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='category/classify.png', upload_to='category'),
        ),
        migrations.AlterField(
            model_name='good',
            name='image',
            field=models.ImageField(blank=True, default='product/Amazon-icon.png', upload_to='product'),
        ),
    ]
