# Generated by Django 2.0 on 2018-04-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20180427_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aorder',
            name='userid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
