# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-23 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20180423_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
