# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-23 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20180423_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
