# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-23 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20180423_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
